### ISSUE TITLE
v3.0.0 changed exports

### ISSUE THREAD

**Issue by 3cp** [hcodes/isutf8#10]
Pls update the readme sample code.

In commonjs env
```js
const isUtf8 = require('isutf8');
```
doesn't work anymore. Need to get the default export

```js
const isUtf8 = require('isutf8').default;
```

**Comment by hcodes** [comment]
Thanks, I'll fix it soon.

**Comment by hcodes** [comment]
v3.1.0

**Comment by hcodes** [comment]
`const isUtf8 = require('isutf8');`
