### ISSUE TITLE
isutf8 3.1.0 Breaks TypeScript Usage With Default Import

### ISSUE THREAD

**Issue by NickGerleman** [hcodes/isutf8#12]
https://github.com/hcodes/isutf8/commit/8ac4a8cfe6f316f80b5c74039fdc56d833725fa4#diff-090b05cdc4c33b5b4d778c13de44d8eaR81 changed from `exports.default = isUtf8` to `module.exports = isUtf8`, but typings still show default export.

In a project with `esModuleInterop` off (default TS setting), we now see errors along the line of `TypeError: (0 , _isutf.default) is not a function`

Context on the call-site:

![image](https://user-images.githubusercontent.com/835219/94167340-3f817700-fe41-11ea-8e84-6b1c70653e08.png)

**Comment by hcodes** [comment]
v3.1.1
Use `esModuleInterop: true` in `tsconfig.json`.
